### ISSUE TITLE
Web Frameworks

### ISSUE THREAD

**Issue by hueniverse** [mikeal/nodeconf2014#22]
I found the Web Framework I co-authored last year to be lacking in substance. While it gave people an idea about what are framework for, about two options people use (hapi, express), and we gave some insight into the internals of express, it was overall a poor use of time.

Lessons:
- don't cover more than one framework
- focus on a specific goal with a framework (static resources for FE, API auth, view rendering, etc.)
- go deep, not wide

I am happy to help with a hapi session.

**Comment by othiym23** [comment]
Isn't Ben Acker already working on a workshopper for Hapi? That seems like it would be a great springboard. Somebody might also be interested in putting something together around koa or a DiY microframework built on top of generators. I'm super ambivalent about them myself, but people are definitely interested.

**Comment by hueniverse** [comment]
Sorry. This is a conference for node, not special V8 flags platform. :-)

**Comment by othiym23** [comment]
I feel you (believe me), but

a. ES6 is coming, whether we're into it or not, and
b. a surprisingly large number of people have asked New Relic about koa support, and I see it discussed a lot on IRC

Generators do make it easy to write async code concisely, and I think the idea of this NodeConf being about modules makes it appealing to use workshopper to teach people how to build up their own little microframework. Those two ideas don't have to be kept together, of course, but I bet people would be into it. I'd be up for trying to put together a workshopper for it myself, for nodeschool.io if not for NodeConf.

**Comment by mikeal** [comment]
We won't be asking attendees to compile node with special flags or training them in technology that isn't ready to be used without default compile flags. All of that stuff is very experimental and I don't think we should be training 300+ people in it. We need to let a few more generator frameworks pop up and battle it out once normal people can run them without flags, when a victor emerges we'll consider having sessions about it, but I don't think we'll be doing sessions where the only person using the technology in production is the author.

On Web Frameworks: I don't want to do this as a formal session this year. The only session we're doing again that we did last year is NodeBots which I actually expect to be quite different.

Instead, we should open up a space for web related workshoppers on the day people arrive, similar to the room we'll have open for "Learn you node" and "Stream Adventure." It would be optional and freeform so people can go after whatever framework they like if it has a workshopper.

**Comment by rvagg** [comment]
@juliangruber said he'd like to do one on Koa (now that he's with segment.io with @visionmedia), he's right in to that stuff.

I'd really like to see @raynos do one on his [http-framework](https://github.com/Raynos/http-framework) material, he's said he'd like to but I'm not sure if he's started. Then we could have:
- http-framework one introducing http stuff just core & small modules
- there's [Express Works](https://github.com/azat-co/expressworks)
- the Hapi one is [here](https://github.com/spumko/makemehapi) (but I don't think that got very far?)
- Koa
- I imagine the PayPal folks pursuing the same route for their [Kraken](https://github.com/paypal/kraken-js)

Perhaps we should be prompting authors and potential authors of these things to get their act together so they can at least be available for an ad-hoc optional session.

**Comment by mikeal** [comment]
Something to keep in mind:

There is a mostly consistent story across the NodeConf content. What is learned in each session can be leveraged in another. You can have a robot that writes to a database you wrote in level that has a visualization in WebGL. This is important, we only have a few days, offering diverging forks and conflicting approaches to the same goal isn't going to work if the goal is to have people internalize the information and create something with it.

This is why people don't even know what session they are going to. For the most part choice is not part of the experience at NodeConf, and that is very intentional. The more attendees are thinking about all these choices the less they are soaking up information and imagining what they can create with it.

I'll put it this way, every time an attendee thinks about whether they should use promises, callbacks or generators they **aren't** thinking about the details of what they are actually trying to create. We're trying to get people comfortable making things not more efficient at having conversations about the best way to make things vs someone else's way of making things. Those conversations are only interesting to 10% of the people there and they'll have those conversations around the fire over beers anyway, we don't need to do anything to help it happen.

**Comment by othiym23** [comment]
Fair enough; my concern is mostly on trying to teach attendees how to fish, not tell them what kind of fish to catch (is it obvious I've been spending too long reading es-discuss?).

I second @rvagg's suggestion to have @raynos do something based on his `http-framework`, which is more or less what I meant when I mentioned a workshopper that teaches people how to write their own microframework. I think teaching people to build their own framework will put them in a much better position to evaluate the existing, popular frameworks, instead of just picking the most popular. And it's pretty easy to write a workshopper around!

**Comment by mikeal** [comment]
We are teaching them to fish, not obsessing about what type of fishing pole to use :)

I think @raynos may already be doing such a workshopper and it would naturally be available in the freeform room on the arrival day.

**Comment by Raynos** [comment]
I havn't started a workshopper yet but want to build one. I was hoping to crank a workshoppert out before jsfest on that front.
